# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addContactPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddContactPage(object):
    def setupUi(self, AddContactPage):
        AddContactPage.setObjectName("AddContactPage")
        AddContactPage.setFixedSize(320, 160)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../浏览器下载内容/chat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AddContactPage.setWindowIcon(icon)
        AddContactPage.setToolTipDuration(0)
        self.userLabel = QtWidgets.QLabel(AddContactPage)
        self.userLabel.setGeometry(QtCore.QRect(10, 10, 30, 20))
        self.userLabel.setObjectName("userLabel")
        self.friendUsername = QtWidgets.QLineEdit(AddContactPage)
        self.friendUsername.setGeometry(QtCore.QRect(60, 10, 180, 20))
        self.friendUsername.setObjectName("userNameAddr")
        self.publicKeyLabel = QtWidgets.QLabel(AddContactPage)
        self.publicKeyLabel.setGeometry(QtCore.QRect(10, 50, 40, 20))
        self.publicKeyLabel.setObjectName("publicKeyLabel")
        self.publicKeyAddr = QtWidgets.QLineEdit(AddContactPage)
        self.publicKeyAddr.setGeometry(QtCore.QRect(60, 50, 180, 20))
        self.publicKeyAddr.setObjectName("publicKeyAddr")
        self.backupLabel = QtWidgets.QLabel(AddContactPage)
        self.backupLabel.setGeometry(QtCore.QRect(10, 90, 40, 20))
        self.backupLabel.setObjectName("backupLabel")
        self.notes = QtWidgets.QLineEdit(AddContactPage)
        self.notes.setGeometry(QtCore.QRect(60, 90, 241, 20))
        self.notes.setObjectName("backup")
        self.addButton = QtWidgets.QPushButton(AddContactPage)
        self.addButton.setGeometry(QtCore.QRect(130, 130, 50, 20))
        self.addButton.setObjectName("addButton")
        self.selectUserButton = QtWidgets.QPushButton(AddContactPage)
        self.selectUserButton.setGeometry(QtCore.QRect(250, 10, 50, 20))
        self.selectUserButton.setObjectName("selectUserButton")
        self.selectPublicKeyButton = QtWidgets.QPushButton(AddContactPage)
        self.selectPublicKeyButton.setGeometry(QtCore.QRect(250, 50, 50, 20))
        self.selectPublicKeyButton.setObjectName("selectPublicKeyButton")

        self.retranslateUi(AddContactPage)
        QtCore.QMetaObject.connectSlotsByName(AddContactPage)

    def retranslateUi(self, AddContactPage):
        _translate = QtCore.QCoreApplication.translate
        AddContactPage.setWindowTitle(_translate("AddContactPage", "添加联系人"))
        self.userLabel.setText(_translate("AddContactPage", "账号:"))
        self.publicKeyLabel.setText(_translate("AddContactPage", "公钥:"))
        self.backupLabel.setText(_translate("AddContactPage", "备注:"))
        self.addButton.setText(_translate("AddContactPage", "添加"))
        self.selectUserButton.setText(_translate("AddContactPage", "选择..."))
        self.selectPublicKeyButton.setText(_translate("AddContactPage", "选择..."))
