# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homepage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomePage(object):
    def setupUi(self, HomePage):
        HomePage.setObjectName("HomePage")
        # HomePage.resize(700, 500)
        HomePage.setFixedSize(700, 500)
        HomePage.setMaximumSize(QtCore.QSize(700, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./images/chat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        HomePage.setWindowIcon(icon)
        HomePage.setWindowOpacity(1.0)
        HomePage.setStyleSheet("")
        self.editMsgWindow = QtWidgets.QTextEdit(HomePage)
        self.editMsgWindow.setGeometry(QtCore.QRect(250, 410, 450, 90))
        self.editMsgWindow.setStyleSheet("*{\n"
                                         "    background-color:#ffffff;\n"
                                         "    border-style:none;\n"
                                         "}")
        self.editMsgWindow.setObjectName("editMsgWindow")
        self.frame = QtWidgets.QFrame(HomePage)
        self.frame.setGeometry(QtCore.QRect(0, 0, 40, 500))
        self.frame.setStyleSheet("*\n"
                                 "{\n"
                                 "    background-color:#000000;\n"
                                 "    border-style:none;\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.personalInfoButton = QtWidgets.QPushButton(self.frame)
        self.personalInfoButton.setGeometry(QtCore.QRect(7, 10, 25, 25))
        self.personalInfoButton.setText("")
        profile_icon = QtGui.QIcon()
        profile_icon.addPixmap(QtGui.QPixmap("./images/profile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.personalInfoButton.setIconSize(QtCore.QSize(25, 25))
        self.personalInfoButton.setIcon(profile_icon)

        self.loginButton = QtWidgets.QPushButton(self.frame)
        self.loginButton.setGeometry(QtCore.QRect(10, 450, 20, 20))
        self.loginButton.setText("")
        login_icon = QtGui.QIcon()
        login_icon.addPixmap(QtGui.QPixmap("./images/login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loginButton.setIconSize(QtCore.QSize(20, 20))
        self.loginButton.setIcon(login_icon)

        self.frame_2 = QtWidgets.QFrame(HomePage)
        self.frame_2.setGeometry(QtCore.QRect(40, 0, 210, 40))
        self.frame_2.setStyleSheet("*{\n"
                                   "    background-color:#e8e8e7;\n"
                                   "    border-style:none;\n"
                                   "}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.searchText = QtWidgets.QLineEdit(self.frame_2)
        self.searchText.setGeometry(QtCore.QRect(30, 10, 130, 20))
        self.searchText.setStyleSheet("*\n"
                                      "{\n"
                                      "    background-color:#ffffff\n"
                                      "}")
        self.searchText.setText("")
        self.searchText.setObjectName("searchText")
        self.searchLabel = QtWidgets.QLabel(self.frame_2)
        self.searchLabel.setGeometry(QtCore.QRect(5, 10, 20, 20))
        self.searchLabel.setText("")
        self.searchLabel.setPixmap(QtGui.QPixmap("./images/glass.png"))
        self.searchLabel.setScaledContents(True)
        self.searchLabel.setObjectName("searchLabel")
        self.addContactButton = QtWidgets.QPushButton(self.frame_2)
        self.addContactButton.setGeometry(QtCore.QRect(170, 10, 20, 20))
        self.addContactButton.setStyleSheet("*{\n"
                                            "    border-style:none;\n"
                                            "}")
        self.addContactButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./images/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addContactButton.setIcon(icon1)
        self.addContactButton.setIconSize(QtCore.QSize(20, 20))
        self.addContactButton.setObjectName("addContactButton")
        self.frame_3 = QtWidgets.QFrame(HomePage)
        self.frame_3.setGeometry(QtCore.QRect(250, 0, 450, 40))
        self.frame_3.setStyleSheet("*{\n"
                                   "    background-color:#f5f5f5;\n"
                                   "    border-bottom:1px solid #e8e8e8;\n"
                                   "}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.chattingUserName = QtWidgets.QLabel(self.frame_3)
        self.chattingUserName.setGeometry(QtCore.QRect(20, 5, 430, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        self.chattingUserName.setFont(font)
        self.chattingUserName.setStyleSheet("*{\n"
                                            "    border-style:none;\n"
                                            "}")
        self.chattingUserName.setText("")
        self.chattingUserName.setObjectName("chattingUserName")
        self.frame_4 = QtWidgets.QFrame(HomePage)
        self.frame_4.setGeometry(QtCore.QRect(250, 380, 450, 30))
        self.frame_4.setStyleSheet("*{\n"
                                   "    background-color:#ffffff;\n"
                                   "    border-style:none;\n"
                                   "    border-top:1px solid #e8e8e7;\n"
                                   "}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.fileButton = QtWidgets.QPushButton(self.frame_4)
        self.fileButton.setGeometry(QtCore.QRect(20, 7, 20, 20))
        self.fileButton.setStyleSheet("*{\n"
                                      "    border-style:none;\n"
                                      "}")
        self.fileButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./images/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileButton.setIcon(icon2)
        self.fileButton.setIconSize(QtCore.QSize(20, 20))
        self.fileButton.setObjectName("fileButton")
        self.historyButton = QtWidgets.QPushButton(self.frame_4)
        self.historyButton.setGeometry(QtCore.QRect(60, 5, 20, 20))
        self.historyButton.setStyleSheet("*{\n"
                                         "    border-style:none;\n"
                                         "}")
        self.historyButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./images/history.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.historyButton.setIcon(icon3)
        self.historyButton.setIconSize(QtCore.QSize(20, 20))
        self.historyButton.setObjectName("historyButton")
        self.sendButton = QtWidgets.QPushButton(HomePage)
        self.sendButton.setGeometry(QtCore.QRect(630, 470, 50, 20))
        self.sendButton.setStyleSheet("*{\n"
                                      "    background-color:#e8e8e8;\n"
                                      "    border-style:none;\n"
                                      "}")
        self.sendButton.setObjectName("sendButton")
        self.contactList = QtWidgets.QListWidget(HomePage)
        self.contactList.setGeometry(QtCore.QRect(40, 40, 210, 460))
        self.contactList.setStyleSheet("*\n"
                                       "{\n"
                                       "    background-color:#e8e7e7;\n"
                                       "    border-style:none;\n"
                                       "}")
        self.contactList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.contactList.setAutoScrollMargin(16)
        self.contactList.setObjectName("contactList")

        self.msgList = QtWidgets.QListWidget(HomePage)
        self.msgList.setGeometry(QtCore.QRect(250, 40, 450, 340))
        self.msgList.setStyleSheet("QListWidget{\n"
                                   "    background-color:#f5f5f5;\n"
                                   "    border-style:none;\n"
                                   "}\n"
                                   "QListWidget::Item{\n"
                                   "    width:420px;\n"
                                   "    height:100px;"       
                                   "    border-bottom:1px dotted #000000;\n"
                                   "    margin:5px;\n"
                                   "}\n")
        self.msgList.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.msgList.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.msgList.setProperty("isWrapping", False)
        self.msgList.setObjectName("msgList")

        self.retranslateUi(HomePage)
        QtCore.QMetaObject.connectSlotsByName(HomePage)

    def retranslateUi(self, HomePage):
        _translate = QtCore.QCoreApplication.translate
        HomePage.setWindowTitle(_translate("HomePage", "客户端"))
        self.sendButton.setText(_translate("HomePage", "发送"))
