# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginPage(object):
    def setupUi(self, LoginPage):
        LoginPage.setObjectName("LoginPage")
        LoginPage.resize(300, 150)
        LoginPage.setMaximumSize(QtCore.QSize(300, 150))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/chat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        LoginPage.setWindowIcon(icon)
        self.userLabel = QtWidgets.QLabel(LoginPage)
        self.userLabel.setGeometry(QtCore.QRect(20, 20, 40, 20))
        self.userLabel.setObjectName("userLabel")
        self.passwordLabel = QtWidgets.QLabel(LoginPage)
        self.passwordLabel.setGeometry(QtCore.QRect(20, 60, 40, 20))
        self.passwordLabel.setObjectName("passwordLabel")
        self.userNameInput = QtWidgets.QLineEdit(LoginPage)
        self.userNameInput.setGeometry(QtCore.QRect(70, 20, 200, 20))
        self.userNameInput.setObjectName("userNameInput")
        self.passwordInput = QtWidgets.QLineEdit(LoginPage)
        self.passwordInput.setGeometry(QtCore.QRect(70, 60, 200, 20))
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.registerButton = QtWidgets.QPushButton(LoginPage)
        self.registerButton.setGeometry(QtCore.QRect(20, 110, 50, 20))
        self.registerButton.setObjectName("registerButton")
        self.loginButton = QtWidgets.QPushButton(LoginPage)
        self.loginButton.setGeometry(QtCore.QRect(220, 110, 50, 20))
        self.loginButton.setObjectName("loginButton")

        self.retranslateUi(LoginPage)
        QtCore.QMetaObject.connectSlotsByName(LoginPage)

    def retranslateUi(self, LoginPage):
        _translate = QtCore.QCoreApplication.translate
        LoginPage.setWindowTitle(_translate("LoginPage", "登录"))
        self.userLabel.setText(_translate("LoginPage", "账号:"))
        self.passwordLabel.setText(_translate("LoginPage", "密码:"))
        self.registerButton.setText(_translate("LoginPage", "注册"))
        self.loginButton.setText(_translate("LoginPage", "登录"))
