# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'personnalInfoPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PersonalInfoPage(object):
    def setupUi(self, PersonalInfoPage):
        PersonalInfoPage.setObjectName("PersonalInfoPage")
        PersonalInfoPage.resize(300, 120)
        PersonalInfoPage.setMaximumSize(QtCore.QSize(300, 120))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/chat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PersonalInfoPage.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(PersonalInfoPage)
        self.label.setGeometry(QtCore.QRect(20, 20, 50, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(PersonalInfoPage)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 50, 20))
        self.label_2.setObjectName("label_2")
        self.usernameLabel = QtWidgets.QLabel(PersonalInfoPage)
        self.usernameLabel.setGeometry(QtCore.QRect(100, 20, 180, 20))
        self.usernameLabel.setObjectName("usernameLabel")
        self.serverLabel = QtWidgets.QLabel(PersonalInfoPage)
        self.serverLabel.setGeometry(QtCore.QRect(100, 70, 180, 20))
        self.serverLabel.setObjectName("serverLabel")

        self.retranslateUi(PersonalInfoPage)
        QtCore.QMetaObject.connectSlotsByName(PersonalInfoPage)

    def retranslateUi(self, PersonalInfoPage):
        _translate = QtCore.QCoreApplication.translate
        PersonalInfoPage.setWindowTitle(_translate("PersonalInfoPage", "个人信息"))
        self.label.setText(_translate("PersonalInfoPage", "账号:"))
        self.label_2.setText(_translate("PersonalInfoPage", "服务器:"))
        self.usernameLabel.setText(_translate("PersonalInfoPage", "null"))
        self.serverLabel.setText(_translate("PersonalInfoPage", "null"))
