# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registerPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegisterPage(object):
    def setupUi(self, RegisterPage):
        RegisterPage.setObjectName("RegisterPage")
        RegisterPage.resize(320, 210)
        RegisterPage.setMaximumSize(QtCore.QSize(320, 210))
        self.userNameLabel = QtWidgets.QLabel(RegisterPage)
        self.userNameLabel.setGeometry(QtCore.QRect(20, 20, 30, 20))
        self.userNameLabel.setObjectName("userNameLabel")
        self.privateKeyLabel = QtWidgets.QLabel(RegisterPage)
        self.privateKeyLabel.setGeometry(QtCore.QRect(20, 100, 30, 20))
        self.privateKeyLabel.setObjectName("privateKeyLabel")
        self.publicKeyLabel = QtWidgets.QLabel(RegisterPage)
        self.publicKeyLabel.setGeometry(QtCore.QRect(20, 60, 30, 20))
        self.publicKeyLabel.setObjectName("publicKeyLabel")
        self.userName = QtWidgets.QLineEdit(RegisterPage)
        self.userName.setGeometry(QtCore.QRect(60, 20, 180, 20))
        self.userName.setObjectName("userName")
        self.publicKeyAddr = QtWidgets.QLineEdit(RegisterPage)
        self.publicKeyAddr.setGeometry(QtCore.QRect(60, 60, 180, 20))
        self.publicKeyAddr.setObjectName("publicKeyAddr")
        self.privateKeyAddr = QtWidgets.QLineEdit(RegisterPage)
        self.privateKeyAddr.setGeometry(QtCore.QRect(60, 100, 180, 20))
        self.privateKeyAddr.setObjectName("privateKeyAddr")
        self.registerButton = QtWidgets.QPushButton(RegisterPage)
        self.registerButton.setGeometry(QtCore.QRect(130, 180, 50, 20))
        self.registerButton.setObjectName("registerButton")
        self.selectUserButton = QtWidgets.QPushButton(RegisterPage)
        self.selectUserButton.setGeometry(QtCore.QRect(250, 20, 50, 20))
        self.selectUserButton.setObjectName("selectUserButton")
        self.selectPublicKeyButton = QtWidgets.QPushButton(RegisterPage)
        self.selectPublicKeyButton.setGeometry(QtCore.QRect(250, 60, 50, 20))
        self.selectPublicKeyButton.setObjectName("selectPublicKeyButton")
        self.selectPrivateKeyButton = QtWidgets.QPushButton(RegisterPage)
        self.selectPrivateKeyButton.setGeometry(QtCore.QRect(250, 100, 50, 20))
        self.selectPrivateKeyButton.setObjectName("selectPrivateKeyButton")
        self.passwordLabel = QtWidgets.QLabel(RegisterPage)
        self.passwordLabel.setGeometry(QtCore.QRect(20, 140, 30, 20))
        self.passwordLabel.setObjectName("passwordLabel")
        self.password = QtWidgets.QLineEdit(RegisterPage)
        self.password.setGeometry(QtCore.QRect(60, 140, 180, 20))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.selectPasswordButton = QtWidgets.QPushButton(RegisterPage)
        self.selectPasswordButton.setGeometry(QtCore.QRect(250, 140, 50, 20))
        self.selectPasswordButton.setObjectName("selectPasswordButton")

        self.retranslateUi(RegisterPage)
        QtCore.QMetaObject.connectSlotsByName(RegisterPage)

    def retranslateUi(self, RegisterPage):
        _translate = QtCore.QCoreApplication.translate
        RegisterPage.setWindowTitle(_translate("RegisterPage", "注册"))
        self.userNameLabel.setText(_translate("RegisterPage", "账号:"))
        self.privateKeyLabel.setText(_translate("RegisterPage", "私钥:"))
        self.publicKeyLabel.setText(_translate("RegisterPage", "公钥:"))
        self.registerButton.setText(_translate("RegisterPage", "注册"))
        self.selectUserButton.setText(_translate("RegisterPage", "选择..."))
        self.selectPublicKeyButton.setText(_translate("RegisterPage", "选择..."))
        self.selectPrivateKeyButton.setText(_translate("RegisterPage", "选择..."))
        self.passwordLabel.setText(_translate("RegisterPage", "密码:"))
        self.selectPasswordButton.setText(_translate("RegisterPage", "选择..."))
